" Vundle
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'

Plugin 'w0ng/vim-hybrid'
Plugin 'vim-scripts/last256'

Plugin 'othree/html5.vim'
Plugin 'othree/yajs.vim'

Plugin 'leafgarland/typescript-vim'

Plugin 'mustache/vim-mustache-handlebars'

Plugin 'wavded/vim-stylus'
Plugin 'digitaltoad/vim-jade'
Plugin 'elzr/vim-json'
Plugin 'mattn/emmet-vim'
Plugin 'airblade/vim-gitgutter'
Plugin 'editorconfig/editorconfig-vim'

Plugin 'bling/vim-airline'
Plugin 'scrooloose/syntastic'

call vundle#end()
filetype plugin indent on

" GUI
set guifont=Fantasque\ Sans\ Mono\ Regular:h13

" Color scheme
set t_Co=256
let g:hybrid_use_Xresources = 1
set background=dark
color hybrid

" Encoding
set encoding=utf8
set fileformat=unix

" Syntax highlight
syntax on

" Line numbers
set number

" Handle whitespaces
set list
set listchars=tab:»\ " whitespace
" set listchars=eol:¬,tab:»·,trail:~,extends:>,precedes:<,space:␣

" Tabs to spaces
set expandtab
" Smart tabs
set smarttab
" Tabs size=2, only python size=4
set shiftwidth=2
set tabstop=2
set softtabstop=2
autocmd FileType python setl shiftwidth=4 tabstop=4 softtabstop=4 et

" Wipe trailing whitespaces, see http://vim.wikia.com/wiki/Remove_unwanted_spaces#Automatically_removing_all_trailing_whitespace
autocmd BufWritePre * :%s/\s\+$//e


" File completion
set wildmenu
set wildignore+=*.pyc,*.fcgi,*.sock,*.db,*.swp,*.swo,*.meta
set wildmode=list:longest

" Highlight search results
set hlsearch

" Paste mode
set pastetoggle=<F2>

" allow backspacing over everything in insert mode
" http://stackoverflow.com/questions/3534028/mac-terminal-vim-will-only-use-backspace-when-at-the-end-of-a-line
set backspace=indent,eol,start

" Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Airline
let g:airline_left_sep=''  " Slightly fancier than '>'
let g:airline_right_sep='' " Slightly fancier than '<'
