# Set Spaceship ZSH as a prompt
autoload -U promptinit; promptinit
prompt spaceship

SPACESHIP_CHAR_SYMBOL="$ "

alias s="cd $HOME/workspace"

export PATH="$PATH:/usr/local/bin"

# Autocompletion
autoload -Uz compinit && compinit

# Editor
export EDITOR=nvim
export VISUAL=nvim
alias vim=nvim

# emacs style keybinds
bindkey -e

# vi style incremental search
bindkey '^R' history-incremental-search-backward
bindkey '^S' history-incremental-search-forward
bindkey '^P' history-search-backward
bindkey '^N' history-search-forward

# keybinds
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
bindkey '^[[3~' delete-char

# Config alias
alias zshconfig='$EDITOR ~/.zshrc'
alias gitconfig='$EDITOR ~/.gitconfig'
alias vimconfig='$EDITOR ~/.config/nvim/init.vim'

# Better ls
alias ls='ls -FH'
alias ll='ls -lFH'

# Egrep find
f () { egrep -r --color -nr $@; }

# Alias
alias s='cd $HOME/workspace'

# Completion
zstyle ':completion:*' menu select

# History, adopted from oh-my-zsh
HISTFILE=$HOME/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups # ignore duplication command history list
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history # share command history data

# Locale
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Get ip alias
alias ip="ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'"

# Git
alias g=git

# ALT + ARROW
# https://stackoverflow.com/questions/12382499/looking-for-altleftarrowkey-solution-in-zsh
bindkey '[C' forward-word
bindkey '[D' backward-word

export PIPENV_VENV_IN_PROJECT=1
