autoload -Uz colors && colors

PROMPT="%{$fg_no_bold[yellow]%}%~ %{$reset_color%}%# "
RPROMPT="[%{$fg_no_bold[yellow]%}%?%{$reset_color%}]"

# Directory colors
export CLICOLOR=1
export LS_COLORS=exfxcxdxbxegedabagacad

# Editor
export EDITOR=nvim
export VISUAL=nvim

# Alias
alias vim=nvim

# emacs style keybinds
bindkey -e

# vi style incremental search
bindkey '^R' history-incremental-search-backward
bindkey '^S' history-incremental-search-forward
bindkey '^P' history-search-backward
bindkey '^N' history-search-forward

# Config alias
alias zshconfig='$EDITOR ~/.zshrc'
alias gitconfig='$EDITOR ~/.gitconfig'

# Better ls
alias ls='ls -FH'
alias ll='ls -lFH'

# Completion
zstyle ':completion:*' menu select

# History
setopt append_history
setopt share_history
setopt extended_history

# Beep
setopt nobeep
